feat: support isBinary for Vault
external-secrets/kubernetes-external-secrets pull request #449
Opened 2020-07-23 14:52 UTC by ilkh

2020-08-03 15:57 UTC, Flydiverny commented on lib/backends/vault-backend.js
> +        secretResponse.data[property] = Buffer.from(secretResponse.data[property], 'base64').toString('utf8')
This feels kind of scary 😄 I guess its fine to turn it into a string but feels like we have an underlying problem in the code forcing us to write weird code :)
Main issue is probably that the KV backend expects us to return a string in `_get` forcing us to serialise here when we already have an object.

2020-08-05 21:27 UTC, pkrishnath commented
Exactly what i am looking for .. Is there any way to store a base64 encoded value in vault?

2020-10-06 23:00 UTC, Flydiverny commented on lib/backends/vault-backend.js
> +        secretResponse.data[property] = Buffer.from(secretResponse.data[property], 'base64').toString('utf8')
Would it be enough to not do the `toString('utf8')` here, just converting the base64 string to a buffer. later on this buffer will be base64 encoded again as the base class won't mess with buffers. This should put the original value from vault into the secret without it ending up double base64 encoded.

https://github.com/godaddy/kubernetes-external-secrets/blob/c3c27bc427c7129e4e98b5b10e4c5dde146c422d/lib/backends/kv-backend.js#L91-L93

https://github.com/godaddy/kubernetes-external-secrets/blob/c3c27bc427c7129e4e98b5b10e4c5dde146c422d/lib/backends/kv-backend.js#L130

2020-12-09 23:11 UTC, Flydiverny requested changes
Needs rebase and comments to be addressed. Should try returning a buffer from vault-backends get instead of a binary string.

2020-12-22 01:27 UTC, Flydiverny commented
Closing this in favor of #585

2020-12-22 01:27 UTC, closed without merging