use rbac.authorization.k8s.io/v1 for ClusterRole/Bindings where k8s >…
external-secrets/kubernetes-external-secrets pull request #609
Opened 2021-01-28 11:06 UTC by AdallomRoy

…= 1.17

2021-01-28 11:13 UTC, AdallomRoy commented
Fixed #516
Based on https://github.com/external-secrets/kubernetes-external-secrets/pull/581, but fixed tests.

2021-01-29 07:49 UTC, moolen requested changes
Hey, thanks for picking this up!

I think there's a typo in the [semverCompare](https://helm.sh/docs/chart_template_guide/function_list/#semvercompare) function. I tried it out locally, with `>=1.17.0` it works fine!

For the record: `rbac.authorization.k8s.io/v1beta1` was deprecated with 1.17 and will be removed with 1.22

2021-01-29 07:49 UTC, moolen commented on charts/kubernetes-external-secrets/templates/rbac.yaml
> +  {{- if semverCompare ">=1.17-0" .Capabilities.KubeVersion.GitVersion -}}
```suggestion
  {{- if semverCompare ">=1.17.0" .Capabilities.KubeVersion.GitVersion -}}
```

2021-01-29 07:49 UTC, moolen commented on charts/kubernetes-external-secrets/templates/rbac.yaml
> +{{ if semverCompare ">=1.17-0" .Capabilities.KubeVersion.GitVersion -}}
```suggestion
{{ if semverCompare ">=1.17.0" .Capabilities.KubeVersion.GitVersion -}}
```

2021-01-29 07:49 UTC, moolen commented on charts/kubernetes-external-secrets/templates/rbac.yaml
> +{{ if semverCompare ">=1.17-0" .Capabilities.KubeVersion.GitVersion -}}
```suggestion
{{ if semverCompare ">=1.17.0" .Capabilities.KubeVersion.GitVersion -}}
```

2021-01-30 10:01 UTC, AdallomRoy commented
Thanks for your CR. Fixed.

2021-01-30 13:09 UTC, moolen approved these changes
thank you for your contribution :heart: !

2021-01-30 13:10 UTC, merged